<template>
  <svg
    width="22"
    height="22"
    viewBox="0 0 22 22"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      x="1"
      y="1"
      width="20"
      height="20"
      rx="10"
      fill="white"
    />
    <rect
      x="1"
      y="1"
      width="20"
      height="20"
      rx="10"
      stroke="#20263A"
      stroke-width="2"
    />
    <circle
      cx="11"
      cy="11"
      r="2.475"
      fill="currentColor"
      stroke="currentColor"
      stroke-width="0.55"
    />
  </svg>
</template>
